language: go
go:
- master

cache:
    directories:
      - $HOME/.cache/go-build
      - $HOME/gopath/pkg/mod

before_install: make setup && make build

notifications:
    email: false

script: make test